#!/bin/bash            # this line only there to enable syntax highlighting in this file

# --------------------------------------- Finite-volume Godunov methods (choose one, or SPH)
HYDRO_MESHLESS_FINITE_MASS     # solve hydro using the mesh-free Lagrangian (fixed-mass) finite-volume Godunov method
#HYDRO_MESHLESS_FINITE_VOLUME   # solve hydro using the mesh-free (quasi-Lagrangian) finite-volume Godunov method (control mesh motion with HYDRO_FIX_MESH_MOTION)
#HYDRO_REGULAR_GRID             # solve hydro equations on a regular (recti-linear) Cartesian mesh (grid) with a finite-volume Godunov method
## -----------------------------------------------------------------------------------------------------
# --------------------------------------- Options to explicitly control the mesh motion (for use with the MFV or grid solvers): only set for non-standard behavior
#BBH

EOS_GAMMA=5./3

KERNEL_FUNCTION=7



NOGRAVITY                # turn off self-gravity (compatible with GRAVITY_ANALYTIC); setting NOGRAVITY gives identical functionality
#GRAVITY_NOT_PERIODIC           # self-gravity is not periodic, even though the rest of the box is periodic
## -----------------------------------------------------------------------------------------------------
ANALYTIC_GRAVITY               # specific analytic gravitational force to use instead of or with self-gravity. If set to a numerical value
ANALYTIC_STAR                                #  > 0 (e.g. =1), then BH_CALC_DISTANCES will be enabled, and it will use the nearest BH particle as the center for analytic gravity computations
#DISKIC

#RELAXIC

HAVE_HDF5
CLIPPING

#DISABLE_ALIGNED_ALLOC


ASSIGN_NEW_IDS                 # assign IDs on startup instead of reading from ICs
#PREVENT_PARTICLE_MERGE_SPLIT   # don't allow gas particle splitting/merging operations
#MERGESPLIT_HARDCODE_MAX_MASS=(6.25e-11)
#MERGESPLIT_HARDCODE_MAX_MASS=(2.5e-10)
#OUTPUT_TIMESTEP
