#!/bin/bash
galaxy="galaxy"
galaxy=$galaxy$1
echo $galaxy
#mv /scratch/snx3000/hpdeng/gizmout/$galaxy/snapshot* /scratch/snx3000/hpdeng/gizmobak/$galaxy
#rm /scratch/snx3000/hpdeng/gizmout/$galaxy/galaxy*
#cp /users/hpdeng/gizmo/scripts/mhd-ics.hdf5 /scratch/snx3000/hpdeng/gizmout/$galaxy/init/$galaxy-ics.hdf5
cp ../$galaxy.conf ../Config.sh
cd ../
make clean
make
mv GIZMO_config.h /scratch/snx3000/hpdeng/gizmout/$galaxy/
cp GIZMO /scratch/snx3000/hpdeng/gizmout/$galaxy/init/
cd /scratch/snx3000/hpdeng
cp /users/hpdeng/gizmo/job/$galaxy.job ./
sbatch $galaxy.job
rm $galaxy.job
