#!/bin/bash
moon="moon"
moon=$moon$1
echo $moon
#mv /scratch/snx3000/hpdeng/gizmout/$moon/snapshot* /scratch/snx3000/hpdeng/gizmobak/$moon
#rm /scratch/snx3000/hpdeng/gizmout/$moon/moon*
#cp /users/hpdeng/gizmo/scripts/mhd-ics.hdf5 /scratch/snx3000/hpdeng/gizmout/$moon/init/$moon-ics.hdf5
cp ../$impact.conf ../Config.sh
cd ../
make clean
make
mv GIZMO_config.h /sh2/home/denghpjn457/scratch/$moon/
cp GIZMO /sh2/home/denghpjn457/scratch/$moon/init
cd /sh2/home/denghpjn457/scratch/$moon/
cp /sh2/home/denghpjn457/planetg/job/$moon.job ./
sbatch $moon.job

