# coding: utf-8
f, axs = plt.subplots(2,3)
a=axs[0,0]
b=axs[0,1]
c=axs[0,2]
d=axs[1,0]
e=axs[1,1]
g=axs[1,2]
axcolor = f.add_axes([0.90, 0.12, 0.02, 0.76])
a.xaxis.set_visible(False)
a.yaxis.set_visible(False)
b.xaxis.set_visible(False)
b.yaxis.set_visible(False)
c.xaxis.set_visible(False)
c.yaxis.set_visible(False)
d.xaxis.set_visible(False)
d.yaxis.set_visible(False)
e.xaxis.set_visible(False)
e.yaxis.set_visible(False)
g.xaxis.set_visible(False)
g.yaxis.set_visible(False)
s1=pynbody.load("/scratch/snx3000/hpdeng/gizmout/nicesnap/vort/lr.hdf5")
pynbody.analysis.halo.center(s1.g,mode='com')
im=sph.image(s1.g,qty="rho",width=50,cmap="jet",units="g cm^-2",log=True,resolution=1000,vmin=100,vmax=1e5,show_cbar=False,noplot=True)
im=np.flipud(im)
aim= a.matshow(im, cmap="jet", norm=LogNorm(vmin=1e2, vmax=1e5))
s1=pynbody.load("/scratch/snx3000/hpdeng/gizmout/nicesnap/vort/hr.hdf5")
pynbody.analysis.halo.center(s1.g,mode='com')
im=sph.image(s1.g,qty="rho",width=50,cmap="jet",units="g cm^-2",log=True,resolution=1000,vmin=100,vmax=1e5,show_cbar=False,noplot=True)
im=np.flipud(im)
bim= b.matshow(im, cmap="jet", norm=LogNorm(vmin=1e2, vmax=1e5))
s1=pynbody.load("/scratch/snx3000/hpdeng/gizmout/nicesnap/vort/uhr.hdf5")
pynbody.analysis.halo.center(s1.g,mode='com')
im=sph.image(s1.g,qty="rho",width=50,cmap="jet",units="g cm^-2",log=True,resolution=1000,vmin=100,vmax=1e5,show_cbar=False,noplot=True)
im=np.flipud(im)
cim= c.matshow(im, cmap="jet", norm=LogNorm(vmin=1e2, vmax=1e5))
c.add_patch(Rectangle((490,290),50,40,fill=None,color='red'))
s1=pynbody.load("/scratch/snx3000/hpdeng/gizmout/nicesnap/resolution/ticlr.hdf5")
pynbody.analysis.halo.center(s1.g,mode='com')
im=sph.image(s1.g,qty="u",width=50,cmap="jet",show_cbar=False,av_z=False,vmin=1e-2,vmax=1.,noplot=True)
im=np.flipud(im)
dim= d.matshow(im, cmap="jet", norm=LogNorm(vmin=1e-2, vmax=1))
dim= d.matshow(im, cmap="jet", norm=LogNorm(vmin=1e2, vmax=1e5))
im=sph.image(s1.g,qty="rho",width=50,cmap="jet",units="g cm^-2",log=True,resolution=1000,vmin=100,vmax=1e5,show_cbar=False,noplot=True)
im=np.flipud(im)
dim= d.matshow(im, cmap="jet", norm=LogNorm(vmin=1e2, vmax=1e5))
s1=pynbody.load("/scratch/snx3000/hpdeng/gizmout/nicesnap/resolution/tichr.hdf5")
pynbody.analysis.halo.center(s1.g,mode='com')
im=sph.image(s1.g,qty="rho",width=50,cmap="jet",units="g cm^-2",log=True,resolution=1000,vmin=100,vmax=1e5,show_cbar=False,noplot=True)
im=np.flipud(im)
eim= e.matshow(im, cmap="jet", norm=LogNorm(vmin=1e2, vmax=1e5))
s1=pynbody.load("/scratch/snx3000/hpdeng/gizmout/nicesnap/resolution/ticuhr.hdf5")
pynbody.analysis.halo.center(s1.g,mode='com')
im=sph.image(s1.g,qty="rho",width=50,cmap="jet",units="g cm^-2",log=True,resolution=1000,vmin=100,vmax=1e5,show_cbar=False,noplot=True)
gim= g.matshow(im, cmap="jet", norm=LogNorm(vmin=1e2, vmax=1e5))
im=np.flipud(im)
gim= g.matshow(im, cmap="jet", norm=LogNorm(vmin=1e2, vmax=1e5))
a.text(60,70,r'MFM_LR_Beta4',fontsize=14,color='yellow')
b.text(60,70,r'MFM_HR_Beta4',fontsize=14,color='yellow')
c.text(60,70,r'MFM_UHR_Beta4',fontsize=14,color='yellow')
d.text(60,70,r'MFM_LR_Beta3.5_TIC',fontsize=14,color='yellow')
e.text(60,70,r'MFM_HR_Beta3.5_TIC',fontsize=14,color='yellow')
g.text(60,70,r'MFM_UHR_Beta3.5_TIC',fontsize=14,color='yellow')
f.colorbar(gim,cax=axcolor)
