# coding: utf-8
s=pynbody.load("snapshot_502.hdf5")
x0=9
pos=s.g["pos"]
mass=s.g["mass"]
xx=pos[:,0]
yy=pos[:,1]
px=xx*mass
py=yy*mass
x1=np.sum(px[np.where(xx>x0)])/np.sum(mass[np.where(xx>x0)])
x2=np.sum(px[np.where(xx<x0)])/np.sum(mass[np.where(xx<x0)])
deltax=x1-x2
y1=np.sum(py[np.where(xx>x0)])/np.sum(mass[np.where(xx>x0)])
y2=np.sum(py[np.where(xx<x0)])/np.sum(mass[np.where(xx<x0)])
deltay=y1-y2
vel=s.g["vel"]
vx=vel[:,0]
vy=vel[:,1]
px=vx*mass
py=vy*mass
vx1=np.sum(px[np.where(xx>x0)])/np.sum(mass[np.where(xx>x0)])
vx2=np.sum(px[np.where(xx<x0)])/np.sum(mass[np.where(xx<x0)])
deltavx=vx1-vx2
vy1=np.sum(py[np.where(xx>x0)])/np.sum(mass[np.where(xx>x0)])
vy2=np.sum(py[np.where(xx<x0)])/np.sum(mass[np.where(xx<x0)])
deltavy=vy1-vy2

vv=deltavx*deltavx+deltavy*deltavy
gp=2*62.46*0.95/np.sqrt(deltax*deltax+deltay*deltay)
vv
gp
